name: Close linked issue on PR merge

on:
  pull_request:
    types:
      - closed

jobs:
  close_issues:
    if: github.event.pull_request.merged == true && github.base_ref == 'develop'
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout üõéÔ∏è
      uses: actions/checkout@v4
      
    - name: Run script
      working-directory: .github/workflows/scripts
      env:
          TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        pip install requests
        python closeDevIssues.py "$TOKEN" jplag JPlag ${{ github.event.pull_request.number }}