name: Deploy Documentation

on:
  push:
    branches:
      - main
    tags: "v**"
    paths:
      - 'docs/**'
      - '.github/workflows/deploy-docs.yml'
  workflow_dispatch:

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
        with:
          token: ${{ secrets.SDQ_DEV_DEPLOY_TOKEN }}
      - uses: actions/checkout@v6
        with:
          repository: ${{ github.repository }}.wiki
          path: wiki
          token: ${{ secrets.SDQ_DEV_DEPLOY_TOKEN }}

      - name: Remove contents in Wiki
        working-directory: wiki
        run: ls -A1 | grep -v '.git' | xargs rm -r

      - name: Copy Wiki from Docs folder
        run: cp -r ./docs/. ./wiki

      - name: Deploy ðŸš€
        uses: stefanzweifel/git-auto-commit-action@v7
        with:
          repository: wiki
